"""add speed_accuracy_mps to session_track_points

Revision ID: 0272e20f8759
Revises: d89555633c3d
Create Date: 2026-09-10 16:37:58.322394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0272e20f8759'
down_revision: Union[str, None] = 'd89555633c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_track_points', sa.Column('speed_accuracy_mps', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_track_points', 'speed_accuracy_mps')
    # ### end Alembic commands ###
