"""add session tracking tables and ended_at

Revision ID: 1735a77e20bd
Revises: d37c5a4d5bf6
Create Date: 2026-08-28 14:22:14.702660

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1735a77e20bd'
down_revision: Union[str, None] = 'd37c5a4d5bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_pauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_pauses_segment_id'), 'session_pauses', ['segment_id'], unique=False)
    op.create_index(op.f('ix_session_pauses_session_id'), 'session_pauses', ['session_id'], unique=False)
    op.create_table('session_track_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('horizontal_accuracy_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_index', name='uq_session_track_points_session_sequence')
    )
    op.create_index(op.f('ix_session_track_points_segment_id'), 'session_track_points', ['segment_id'], unique=False)
    op.create_index(op.f('ix_session_track_points_session_id'), 'session_track_points', ['session_id'], unique=False)
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ended_at')
    op.drop_index(op.f('ix_session_track_points_session_id'), table_name='session_track_points')
    op.drop_index(op.f('ix_session_track_points_segment_id'), table_name='session_track_points')
    op.drop_table('session_track_points')
    op.drop_index(op.f('ix_session_pauses_session_id'), table_name='session_pauses')
    op.drop_index(op.f('ix_session_pauses_segment_id'), table_name='session_pauses')
    op.drop_table('session_pauses')
    # ### end Alembic commands ###
