"""add player_profiles and player_positions

Revision ID: 1b1ea3040d00
Revises: 734a7a80df49
Create Date: 2026-08-21 23:35:22.011243

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b1ea3040d00'
down_revision: Union[str, None] = '734a7a80df49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.create_table('player_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('preferred_foot', sa.String(length=16), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('avatar_public_id', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # GiST index on location is created automatically by GeoAlchemy2 (spatial_index=True).
    op.create_table('player_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_profile_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_profile_id', 'position', name='uq_player_positions_profile_position')
    )
    op.create_index(op.f('ix_player_positions_player_profile_id'), 'player_positions', ['player_profile_id'], unique=False)
    op.create_index('one_preferred_per_player', 'player_positions', ['player_profile_id'], unique=True, postgresql_where=sa.text('is_preferred = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_preferred_per_player', table_name='player_positions', postgresql_where=sa.text('is_preferred = true'))
    op.drop_index(op.f('ix_player_positions_player_profile_id'), table_name='player_positions')
    op.drop_table('player_positions')
    op.execute('DROP INDEX IF EXISTS idx_player_profiles_location')
    op.drop_table('player_profiles')
    # ### end Alembic commands ###
