"""add sessions title and history index

Revision ID: 8b829592aec6
Revises: b5949e05b336
Create Date: 2026-10-05 10:25:29.303010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '8b829592aec6'
down_revision: Union[str, None] = 'b5949e05b336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.Text(), nullable=True))
    op.create_index('ix_sessions_user_started', 'sessions', ['user_id', sa.text('started_at DESC'), sa.text('id DESC')], unique=False, postgresql_where=sa.text('ended_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_user_started', table_name='sessions', postgresql_where=sa.text('ended_at IS NOT NULL'))
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
