"""add session metrics, profile weight/sex, segment_id not null

Revision ID: b5949e05b336
Revises: 0272e20f8759
Create Date: 2026-09-30 09:56:23.655916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5949e05b336'
down_revision: Union[str, None] = '0272e20f8759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('active_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('top_speed_kmh', sa.Float(), nullable=True),
    sa.Column('top_speed_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('sprint_count', sa.Integer(), nullable=True),
    sa.Column('sprint_distance_m', sa.Float(), nullable=True),
    sa.Column('zone_walk_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_jog_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_run_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_high_run_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_sprint_seconds', sa.Integer(), nullable=True),
    sa.Column('calories_kcal', sa.Integer(), nullable=False),
    sa.Column('mass_kg_at_computation', sa.Float(), nullable=False),
    sa.Column('speed_source', sa.String(length=16), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('speed_band_bucket', sa.String(length=16), nullable=False),
    sa.Column('speed_band_boundaries_kmh', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pitch_long_axis_m', sa.Float(), nullable=True),
    sa.Column('accepted_fix_count', sa.Integer(), nullable=False),
    sa.Column('gap_seconds', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingest_flags', postgresql.ARRAY(sa.String(length=32)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('segment_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('active_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('gap_seconds', sa.Integer(), nullable=False),
    sa.Column('top_speed_kmh', sa.Float(), nullable=True),
    sa.Column('sprint_count', sa.Integer(), nullable=True),
    sa.Column('sprint_distance_m', sa.Float(), nullable=True),
    sa.Column('zone_walk_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_jog_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_run_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_high_run_seconds', sa.Integer(), nullable=True),
    sa.Column('zone_sprint_seconds', sa.Integer(), nullable=True),
    sa.Column('calories_kcal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id')
    )
    op.create_table('sprint_efforts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('effort_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('peak_speed_kmh', sa.Float(), nullable=False),
    sa.Column('peak_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['session_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'effort_index', name='uq_sprint_efforts_session_effort_index')
    )
    op.create_index(op.f('ix_sprint_efforts_segment_id'), 'sprint_efforts', ['segment_id'], unique=False)
    op.create_index(op.f('ix_sprint_efforts_session_id'), 'sprint_efforts', ['session_id'], unique=False)
    op.add_column('player_profiles', sa.Column('weight_kg', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('player_profiles', sa.Column('weight_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('player_profiles', sa.Column('sex', sa.String(length=32), nullable=True))
    # Segmentless rows predate training segments and cannot be attributed to any
    # segment (0.5 §7.3.4 drops them); the downgrade does not restore them.
    op.execute('DELETE FROM session_pauses WHERE segment_id IS NULL')
    op.execute('DELETE FROM session_track_points WHERE segment_id IS NULL')
    op.alter_column('session_pauses', 'segment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('session_track_points', 'segment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_track_points', 'segment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('session_pauses', 'segment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('player_profiles', 'sex')
    op.drop_column('player_profiles', 'weight_updated_at')
    op.drop_column('player_profiles', 'weight_kg')
    op.drop_index(op.f('ix_sprint_efforts_session_id'), table_name='sprint_efforts')
    op.drop_index(op.f('ix_sprint_efforts_segment_id'), table_name='sprint_efforts')
    op.drop_table('sprint_efforts')
    op.drop_table('segment_metrics')
    op.drop_table('session_metrics')
    # ### end Alembic commands ###
