"""add pitches, user_saved_pitches, sessions, and session_segments

Revision ID: d37c5a4d5bf6
Revises: 1b1ea3040d00
Create Date: 2026-08-25 17:31:02.420780

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd37c5a4d5bf6'
down_revision: Union[str, None] = '1b1ea3040d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('end_a_corner_1', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('end_a_corner_2', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('end_b_corner_1', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('end_b_corner_2', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST indexes on corner geographies are created automatically by GeoAlchemy2
    # (spatial_index=True). Do not also call op.create_index for them.
    op.create_index(op.f('ix_pitches_created_by_user_id'), 'pitches', ['created_by_user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=16), nullable=False),
    sa.Column('play_structure', sa.String(length=16), nullable=False),
    sa.Column('planned_segment_length_minutes', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_pitch_id'), 'sessions', ['pitch_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_saved_pitches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pitch_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pitch_id', name='uq_user_saved_pitches_user_pitch')
    )
    op.create_index(op.f('ix_user_saved_pitches_pitch_id'), 'user_saved_pitches', ['pitch_id'], unique=False)
    op.create_index(op.f('ix_user_saved_pitches_user_id'), 'user_saved_pitches', ['user_id'], unique=False)
    op.create_table('session_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('attack_direction', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'segment_index', name='uq_session_segments_session_index')
    )
    op.create_index(op.f('ix_session_segments_session_id'), 'session_segments', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_segments_session_id'), table_name='session_segments')
    op.drop_table('session_segments')
    op.drop_index(op.f('ix_user_saved_pitches_user_id'), table_name='user_saved_pitches')
    op.drop_index(op.f('ix_user_saved_pitches_pitch_id'), table_name='user_saved_pitches')
    op.drop_table('user_saved_pitches')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_pitch_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_pitches_created_by_user_id'), table_name='pitches')
    op.execute('DROP INDEX IF EXISTS idx_pitches_end_b_corner_2')
    op.execute('DROP INDEX IF EXISTS idx_pitches_end_b_corner_1')
    op.execute('DROP INDEX IF EXISTS idx_pitches_end_a_corner_2')
    op.execute('DROP INDEX IF EXISTS idx_pitches_end_a_corner_1')
    op.drop_table('pitches')
    # ### end Alembic commands ###
