"""session structure extensions extra time and training activities

Revision ID: d89555633c3d
Revises: 1735a77e20bd
Create Date: 2026-09-07 13:17:31.325342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd89555633c3d'
down_revision: Union[str, None] = '1735a77e20bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_segments', sa.Column('activity_kind', sa.String(length=16), nullable=True))
    op.add_column('sessions', sa.Column('extra_time_enabled', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('planned_extra_time_segment_length_minutes', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('training_activity_options', postgresql.ARRAY(sa.String(length=16)), nullable=True))
    op.alter_column('sessions', 'play_structure',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.execute(
        """
        UPDATE sessions
        SET play_structure = 'training_activities'
        WHERE play_structure = 'open'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE sessions
        SET play_structure = 'open'
        WHERE play_structure = 'training_activities'
        """
    )
    op.alter_column('sessions', 'play_structure',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('sessions', 'training_activity_options')
    op.drop_column('sessions', 'planned_extra_time_segment_length_minutes')
    op.drop_column('sessions', 'extra_time_enabled')
    op.drop_column('session_segments', 'activity_kind')
    # ### end Alembic commands ###
